### ISSUE TITLE
Te reto a que alcances el throughput de nuestro TP

### ISSUE THREAD

**Issue by david-wis** [ThomasMiz/mail-devil#1]
[Comentarios](https://github.com/j0liu/POP3-Server/wiki/Algunos-comentarios...)

**Comment by ThomasMiz** [comment]
JJJAJAAJAJJAJ flaco que hacés acá

Ojo que este está hecho en Rust, tokio por debajo multiplexa tareas en un solo thread usando `epoll`

**Comment by ThomasMiz** [comment]
[done](https://github.com/j0liu/POP3-Server/issues/1)
